apiVersion: nirmata.io/v1alpha1
kind: ImageVerificationPolicy
metadata:
  name: test
spec:
  rules:
    - name: cosign-keyless
      match: 
        any:
          - (length(containerDefinitions) > `0`): true
      imageExtractors:
        - name: test
          path: /containerDefinitions/*/image/
      verify:
      - imageReferences: 
        - ghcr.io/*
        cosign:
          - keyless:
              issuer: https://token.actions.githubusercontent.com
              subject: https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/heads/main
            rekor:
              url: https://rekor.sigstore.dev
            ignoreSCT: true
            intotoAttestations:
            - type: https://slsa.dev/provenance/v0.2
              conditions:
              - all:
                - key: '{{ regex_match(''^https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/heads/main'',''{{
                    builder.id}}'') }}'
                  operator: Equals
                  value: true
