apiVersion: nirmata.io/v1alpha1
kind: ImageVerificationPolicy
metadata:
  name: test
spec:
  rules:
    - name: cosign-keyless
      match: 
        any:
          - (length(containerDefinitions) > `0`): true
      imageExtractors:
        - name: test
          path: /containerDefinitions/*/image/
      verify:
      - imageReferences: ghcr.io/*
        cosign:
          - keyless:
              issuer: https://accounts.google.com
              subject: vishal.choudhary@nirmata.com
            rekor:
              pubKey: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
                kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
                -----END PUBLIC KEY-----
            ignoreSCT: true
